---
- name: Install git
  become: true
  ansible.builtin.yum:
    name: git
    state: present
- name: Copy Lighthouse from git
  ansible.builtin.git:
    repo: "{{ lighthouse_vcs }}"
    version: master
    dest: "{{ lighthouse_dir }}"
  register: copy_remote
- name: Create Lighthouse config
  become: true
  ansible.builtin.template:
    src: default.conf.j2
    dest: /etc/nginx/conf.d/default.conf
    mode: 0644
  notify: Reload-nginx
